# Generated by Django 2.1 on 2018-10-12 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedProducts',
            fields=[
                ('issuance_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('units', models.CharField(choices=[('mls', 'Milliliters'), ('pls', 'Pellets')], max_length=11)),
                ('jen_no', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('totals', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Client')),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=15)),
                ('units', models.CharField(choices=[('mls', 'Milliliters'), ('pls', 'Pellets')], max_length=11)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedProducts',
            fields=[
                ('reception_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('units', models.CharField(choices=[('mls', 'Milliliters'), ('pls', 'Pellets')], max_length=11)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('totals', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Products')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnedProducts',
            fields=[
                ('return_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('units', models.CharField(choices=[('mls', 'Milliliters'), ('pls', 'Pellets')], max_length=11)),
                ('jen_no', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('totals', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Products')),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='issuedproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Products'),
        ),
    ]
